fileVersion: 1
id: "9"
mappingDefinitions:
  SAMPLE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  WORK:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
name: New Environment
type: Environment
